lab03: student.c File Reference
student.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <time.h>
Data Structures
struct student
Typedefs
typedef struct student student
Functions
student * make_student (char *name, int age, int gradYear)
void printStudent (student *diwalky)
int randomChar ()
int randomInt (int max, int min)
char * randomString (int length)
student * randStudent ()
student ** makeStudentArray (int count)
void printStudentArray (student **studArray, int count)
student ** copyStudArrayShallow (int count, student **oldStudArray)
void freeStudentArray (int count, student **studArray)
int main ()
Typedef Documentation
student
typedef struct student student
Function Documentation
copyStudArrayShallow()
student** copyStudArrayShallow (int count, student ** oldStudArray)
Referenced by main().
freeStudentArray()
void freeStudentArray (int count, student ** studArray)
References student::age, and student::name.
Referenced by main().
main()
int main ()
References copyStudArrayShallow(), freeStudentArray(), make_student(), makeStudentArray(), printStudent(), printStudentArray(), and randomChar().
make_student()
student* make_student (char * name, int age, int gradYear)
Referenced by main(), and randStudent().
makeStudentArray()
student** makeStudentArray (int count)
References randStudent().
Referenced by main().
printStudent()
void printStudent (student * diwalky)
References student::age, and student::name.
Referenced by main(), and printStudentArray().
printStudentArray()
void printStudentArray (student ** studArray, int count)
References printStudent().
Referenced by main().
randomChar()
int randomChar ()
Referenced by main(), and randomString().
randomInt()
int randomInt (int max, int min)
Referenced by randStudent().
randomString()
char* randomString (int length)
References randomChar().
Referenced by randStudent().
randStudent()
student* randStudent ()
References make_student(), randomInt(), and randomString().
Referenced by makeStudentArray().