hw2: array_sort.c File Reference
array_sort.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "array_sort.h"
Functions
void bubble_sort (double a[], int array_size)
void bubble_sort_int (int a[], int array_size)
int generate_random_int (int max)
void fill_array_with_randoms (int a[], int array_size, int max)
Function Documentation
bubble_sort()
void bubble_sort (double a[], int array_size)
file array_sort.c @Sean
Functions for sorting arrays. Sorts an array of doubles into ascending order by bubble sort
Parameters
The Array to sort
array_size The size of the array
Referenced by main().
bubble_sort_int()
void bubble_sort_int (int a[], int array_size)
Referenced by main().
fill_array_with_randoms()
void fill_array_with_randoms (int a[], int array_size, int max)
Fills an array with random integers
Parameters
The Array to fill
array_size The size of the array
the maximum possible value of each integer in the array
References generate_random_int().
Referenced by main().
generate_random_int()
int generate_random_int (int max)
Generates a random integer
Parameters
The maximum value of the random integer to be generated
Returns
the randomly genereated integer
Referenced by fill_array_with_randoms().